chore: clean up baseUrl
porscheofficial/porscheofficial.github.io pull request #30
Opened 2023-11-07 15:49 UTC by MarcelKnobelsdorf

Closes #

## 📑 Description

## ✅ Checks
- [ ] I have read and accept the [Contributor License Agreement](https://opensource.porsche.com/docs/cla)

2023-11-08 08:35 UTC, pboeder commented on package.json
> +    "start": "http-server out -p 3001",
Did you commit that line intentionally?

2023-11-08 08:36 UTC, pboeder requested changes

2023-11-08 08:36 UTC, pboeder commented on package.json
> +    "dotenv": "16.3.1",
peerDependency

2023-11-08 15:21 UTC, MarcelKnobelsdorf commented on package.json
> +    "start": "http-server out -p 3001",
Thanks for the hint. I will undo it

2023-11-09 07:33 UTC, itrich approved these changes
LGTM! :shipit:

2023-11-09 07:34 UTC, pboeder approved these changes

2023-11-13 10:56 UTC, merged